version: '2.4'
services:
  postgres:
    container_name: postgres
    image: postgres:12.0
    environment:
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: tom
    ports:
      - 5432:5432
#    volumes:
#      - ./dbdata:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U tom
      interval: 10s
      retries: 10
  prototype:
    container_name: prototype-quarkus
    image: quarkus/prototype-quarkus:v1
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
